# Generated by Django 5.0.6 on 2024-05-13 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0013_alter_book_price"),
        ("wishlist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userwishlist",
            unique_together={("user", "book")},
        ),
        migrations.AddField(
            model_name="userwishlist",
            name="book",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist",
                to="books.book",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userwishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="userwishlist",
            name="product",
        ),
    ]
