# Generated by Django 5.0.6 on 2024-05-13 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "wishlist",
            "0002_alter_userwishlist_unique_together_userwishlist_book_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userwishlist",
            unique_together=set(),
        ),
    ]
