# Generated by Django 5.0.6 on 2024-05-13 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0002_alter_userwishlist_unique_together"),
        ("wishlist", "0003_alter_userwishlist_unique_together"),
    ]

    operations = []
