# Generated by Django 5.0.6 on 2024-05-09 14:45

import books.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=1)),
                ("image", models.ImageField(upload_to=books.models.book_cover_path)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book",
                to="books.bookimage",
            ),
        ),
    ]
