# Generated by Django 5.0.6 on 2024-05-09 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_alter_book_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="image",
        ),
        migrations.RemoveField(
            model_name="book",
            name="views",
        ),
        migrations.AddField(
            model_name="bookimage",
            name="book",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="books.book",
            ),
        ),
    ]
