# Generated by Django 5.0.6 on 2024-05-09 21:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_remove_book_image_remove_book_views_bookimage_book"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="viewers",
            unique_together={("user", "book")},
        ),
    ]
