# Generated by Django 5.0.6 on 2024-05-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0007_alter_viewers_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="bookimage",
            name="slug",
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="viewers",
            name="count",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="viewers",
            name="slug",
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
