# Generated by Django 5.0.6 on 2024-05-10 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_alter_book_slug_alter_bookimage_slug_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewers",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="book_viewers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
