# Generated by Django 5.0.6 on 2024-05-10 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0010_book_borrower"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="is_borrowed",
        ),
    ]
