# Generated by Django 5.0.6 on 2024-05-09 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={"verbose_name": "rating", "verbose_name_plural": "ratings"},
        ),
    ]
