# Generated by Django 5.0.6 on 2024-05-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0002_alter_rating_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="slug",
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
