# Generated by Django 5.0.6 on 2024-05-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0003_alter_rating_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
