# Generated by Django 5.0.6 on 2024-05-13 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserWishList",
        ),
    ]
